# Generated by Django 3.1.2 on 2020-10-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20201022_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='email',
            new_name='profile',
        ),
    ]
