# Generated by Django 3.1.2 on 2020-10-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20201022_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='profile',
        ),
    ]
