# Generated by Django 3.1.2 on 2020-10-24 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_books_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_posted',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
