# Generated by Django 3.1.2 on 2020-10-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_books_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
